### ISSUE TITLE
Set License problem

### ISSUE THREAD

**Issue by masum1161** [DeepARSDK/quickstart-android-java#12]
No implementation found for void ai.deepar.ar.DeepAR.setLicenseKeyN(java.lang.String) (tried Java_ai_deepar_ar_DeepAR_setLicenseKeyN and Java_ai_deepar_ar_DeepAR_setLicenseKeyN__Ljava_lang_String_2)

**Comment by Sikter** [comment]
I would assume this could be proguard issue when you build release version. Please make sure to set adequate Proguard rules as explained in our [Getting started guide](https://help.deepar.ai/en/articles/3435817-getting-started):
<img width="726" alt="Screenshot 2021-03-15 at 11 30 40" src="https://user-images.githubusercontent.com/2507180/111139808-e093f380-8581-11eb-9fac-1a97c016b539.png">
