### ISSUE TITLE
Fatal signal 7 (SIGBUS), code 1, fault addr 0xb93f4968 in tid 26455

### ISSUE THREAD

**Issue by polokoio456** [DeepARSDK/quickstart-android-java#14]
I encounter a crash with HTC M8 (OS 6.0).

I just see some log with this...

```
E/Looper: Invalid attempt to set NULL callback but not allowed for this looper.
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb91fc078
A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0xb93f4968 in tid 26455
```

If I remove DeepAR.setRenderSurface(), it would not crash.
I think it crash in the aar file.

**Comment by polokoio456** [comment]
I encounter a crash with HTC M8 (OS 6.0).

I just see some log with this...

```
E/Looper: Invalid attempt to set NULL callback but not allowed for this looper.
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb91fc078
A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0xb93f4968 in tid 26455 (ndochat.app.dev)
```

If I remove DeepAR.setRenderSurface(), it would not crash.

**Comment by ibrelm** [comment]
hi bro do you fixed this

**Comment by Sikter** [comment]
We'll look into it thanks for reproting.

**Comment by coolabhi30** [comment]
Coulf you fix this issue

**Comment by PopId-A** [comment]
Any update on this issue yet ?

**Comment by igor-aradski** [comment]
Closing the issue due to lack of recent information. Leave a comment if you still have this problem with the new versions of the SDK.
