### ISSUE TITLE
Not an issue / question on going beyond 720p

### ISSUE THREAD

**Issue by johndpope** [DeepARSDK/quickstart-android-java#19]
We want to record at 1024x1980 9:16

is this on the road map to support?

**Comment by Sikter** [comment]
Hi, our recording API somwhat supports this. Basically, you can take any subframe of the output rendering resolution. From our Android API docs:
**void startVideoRecording(String filePath, int outputWidth, int outputHeight)**
Starts video recording, the outputWidth, and outputHeight parameters can be used to specify output video resolution. The SurfaceView will be skewed to the desired resolution. To preserve the aspect ratio, enter the desired output width or height and set the other parameter to zero.

The max rendering resolution atm is 1920x1080 so your exact use case will not be supported, however, if you use this resolution and set the width to 1024 the height will be 1.820  - this is the limit of our SDK atm.
