### ISSUE TITLE
About video recording where the first couple of frames were black sometimes

### ISSUE THREAD

**Issue by polokoio456** [DeepARSDK/quickstart-android-java#20]
- Fixed video recording bug where the first couple of frames were black sometimes

Hi, guy
I try version 2.3.0 Android SDK, the issue is not still resolved.
My test device is Samsung A30s (OS is Android 10).
Every video can reproduce.

Please help this, thank you.

**Comment by igor-aradski** [comment]
Closing the issue due to lack of recent information. Leave a comment if you still have this problem with the new versions of the SDK.
