### ISSUE TITLE
Error : Invalid output width and/or height

### ISSUE THREAD

**Issue by polokoio456** [DeepARSDK/quickstart-android-java#21]
After I traced code, I found that I set the surface width or height could bigger than `MediaVideoEncoder.getMaxSupportedWidth` or `MediaVideoEncoder.getMaxSupportedHeight`.
( deepAR.setRenderSurface(holder.surface, width, height) ).

So, I faced this Error (Invalid output width and/or height), and I cannot record video.

I suggest it could public those func `MediaVideoEncoder.getMaxSupportedHeight()` and `MediaVideoEncoder.getMaxSupportedWidth()` to use by me.

Thus, I think I will not face this issue.

**Comment by nachiketghelani** [comment]
I am getting the same issue with the video record. In some of the devices working but in some of not so we need to set manually so video resolution not getting proper as per our expectation.

Can anyone help you out here?

**Comment by DishoD** [comment]
You can set the resolution of the camera with `cameraGrabber.setResolutionPreset(CameraResolutionPreset.P1280x720);`. Also you cen set resolution of the output video with `deepAR.startVideoRecording(String filePath, int outputWidth, int outputHeight)`. For more info read our [Android API documentation](https://help.deepar.ai/en/articles/4388115-android-api-documentation).
