### ISSUE TITLE
How to remove "DeepAR.ai" from preview screen?

### ISSUE THREAD

**Issue by fullstact69** [DeepARSDK/quickstart-android-java#23]
![Screenshot_20210219-105758_DeepAR_Example](https://user-images.githubusercontent.com/53449197/108452325-40f58500-72a3-11eb-923d-dbd91e73a5cd.jpg)

**Comment by KumarSunil17** [comment]
Change subscription plan for your project. Check this [pricing docs](https://developer.deepar.ai/pricing).
