### ISSUE TITLE
How to set video frame rate  "Slow", "Medium", "Fast"

### ISSUE THREAD

**Issue by Azharlnsel** [DeepARSDK/quickstart-android-java#24]
How can i set frame rate for video 
I mean video "Slow", "Medium", "Fast" recording

**Comment by Sikter** [comment]
Hi, our CameraGrabber implementation is just an example how one can integrate with camera. If you need any additional camera features (like the one you mentioned) you should handle it in your CameraGrabber implementation. It seems to me to be just a matter of timing the input frames to DeepAR (receiveFrame call).
