### ISSUE TITLE
Could not find :deepar

### ISSUE THREAD

**Issue by ankitahuja0508** [DeepARSDK/quickstart-android-java#33]
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :deepar:.
     Searched in the following locations:
       - file:/Users/ahuja/Aexyn/DeepAR-quickstart-android-java/deepar/deepar.aar
     Required by:
         project :app

can anyone help where can I get deepar.aar file ? its not there in code

**Comment by HNY11** [comment]
Follow this guide 
https://help.deepar.ai/en/articles/3435817-getting-started
