### ISSUE TITLE
Video feed not starting on Samsung devices

### ISSUE THREAD

**Issue by sourcetreehugger** [DeepARSDK/quickstart-android-java#41]
Today I tried your quickstart project in Android Studio. I was able to start the camera feed on an Honor 7 phone, but I was unable to start the camera feed on Samsung devices.

**Steps to reproduce issue**
- Pull the `quickstart-android-java` repository
- Download and install Android Studio version 2022.2.1
- Create a project with bundle id: `com.simontest.deeparandroid`
- Add the application id at line 6 in `app/build.gradle`
- Add the license key at line 340 in `app\src\main\java\ai\deepar\deepar_example\MainActivity.java`
- Press file -> Sync Project with gradle files
- Connect the device
- Build the application to the device

**Symptoms:**
- Camera feed stays black, unable to use UI.

**Devices working**
- Honor 7

**Devices not working**
- Samsung Galaxy A52 Android version 13 
- Samsung Galaxy S20 Android version 13

**Comment by NazarTkachukVakoms** [comment]
@sourcetreehugger which Android version is on Honor 7?

**Comment by sourcetreehugger** [comment]
I borrowed the Honor 7 from a coworker. I presume it is running on a lower version than Android 13, since those devices are not working.

**Comment by NazarTkachukVakoms** [comment]
I suppose you have a problem similar to mine. 
Check this link: https://forum.deepar.ai/t/the-android-deepar-sdk-is-not-initializing-with-targetsdk-33-android-13/355/11

**Comment by sourcetreehugger** [comment]
Just tested out your branch and it works on Galaxy A52!

**Comment by NazarTkachukVakoms** [comment]
Works for me as well! Thanks!

**Comment by djanekovicdeepar** [comment]
Cool, thanks for checking!

We are currently in the process of preparing a new release. Once we deploy it, I am going to merge this branch to master and close this issue. Feel free to open another issue if you have another question or something is not working as expected.

Thanks,
Darko
