### ISSUE TITLE
Camera2 api

### ISSUE THREAD

**Issue by basicemotions** [DeepARSDK/quickstart-android-java#6]
Do you have any examples of how we can use the DeepAR SDK with the Camera2 api?

**Comment by michaeljames91** [comment]
@basicemotions were you able to use DeepAR SDK with Camera2 API? if yes, could you share how you do it?

**Comment by nayelfares** [comment]
I need a sample with Camera2 API

**Comment by bzok2** [comment]
We definitely need a camera2 Support.  come on guys :) !

**Comment by adrienrx** [comment]
Up

**Comment by Sikter** [comment]
Hi, we have it in our development roadmap and will have it soon. Best.
